nav:
    - Introduction: index.md
    - Base-conversion: Base-conversion
    - Digit-DP: Digit-DP
    - LeetCode-7-Reverse-Integer-middle: LeetCode-7-Reverse-Integer-middle    
    - LeetCode-9-回文数: LeetCode-9-回文数    

